POST http://8.215.71.251:7080/audgeneratebase64
Content-Type: application/json

{
  "trace_id": "111",
  "text": "Sure, I'm down for some quality talk time. What's on your mind?",
  "speaker_id": "Binary"
}

###
GET http://8.215.71.251:7080/tts_stream?text=Sure, I'm down for some quality talk time. What's on your mind?&speaker_id=Binary&trace_id=111
Accept: application/json

###


